import { Inter } from "next/font/google";
import "./globals.css";
import MainHeader from "@/components/main-header";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
   weight: ['400', '600', '700']
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable}  antialiased`}
      >
        <MainHeader />
        {children}
      </body>
    </html>
  );
}
